### ISSUE TITLE
Great Work

### ISSUE THREAD

**Issue by nasirxo** [hax0rtahm1d/Reverse-Engineering#1]
Nice to see you decrypting my script . 👍🏻👍🏻👍🏻

**Comment by htr-tech** [comment]
@nasirxo boss i am a fan of yours :)

take love from Bangladesh 😄

**Comment by nasirxo** [comment]
From you work i got you are talented . Keep it up i have something to share
with you lets have a chat https://m.facebook.com/nasir.xo
